### ISSUE TITLE
Found preexisting AWS CLI installation: /usr/local/aws-cli/v2/current. Please rerun install script with --update flag.

### ISSUE THREAD

**Issue by nucks** [unfor19/install-aws-cli-action#1]
When run with: `- uses: unfor19/install-aws-cli-action@v1`

![image](https://user-images.githubusercontent.com/18559697/101084351-12e98a00-356b-11eb-88d1-70477ec52c84.png)

**Comment by unfor19** [comment]
Thank you, fixing it!

**Comment by nucks** [comment]
@unfor19 I see you created an update but the package is still pointing to `1.0` as the latest version. Are you testing the fix?

**Comment by unfor19** [comment]
@nucks release v1.0.1 should do the trick
Tested it here - https://github.com/unfor19/install-aws-cli-action-test/runs/1496146646?check_suite_focus=true

![image](https://user-images.githubusercontent.com/15122452/101107447-0270f800-35db-11eb-9ddf-b919315f55d6.png)

**Comment by nucks** [comment]
Great! I can confirm that it is now fixed. Thanks 😄

**Comment by unfor19** [comment]
@nucks - I removed `v1.0.1 `, I want to keep it simple - please use v1
I'll create v2 if I add any breaking changes, so v1 should always be updated with hotfixes and such

**Comment by nucks** [comment]
Sounds like a great plan!

**Comment by sathish-git123** [comment]
can anyone help me with this?
![image](https://user-images.githubusercontent.com/94332478/161116319-4050fa57-e26b-44c8-8989-f47abc3588c5.png)

**Comment by unfor19** [comment]
@sathish-git123 I'm not sure your issue is related to this project, having said that, you can download the installation script and share your results:

1. Download the installation script
   ```bash
   curl -L -o install-aws-cli.sh https://raw.githubusercontent.com/unfor19/install-aws-cli-action/master/entrypoint.sh && \
   chmod +x /tmp/install-aws-cli.sh
   ```
1. Execute installation script as root (or use `sudo`)
   ```bash
   whoami # if you're root, proceed
   /tmp/install-aws-cli.sh

   # if not root, use sudo
   # sudo /tmp/install-aws-cli.sh
   ```

**Comment by sathish-git123** [comment]
sure i will excute post output thank you for your quick reply.

**Comment by TyrrellS** [comment]
Any chance that you know what the issue is on this? 

![image](https://user-images.githubusercontent.com/103883890/163712484-c79ed5e0-8a23-427f-ad6a-2ed3872a6287.png)

**Comment by unfor19** [comment]
@TyrrellS I'd love to help, though it's hard to understand the issue with this very short print screen.

Please provide what have you tried to do, on which machine, and what was the expected result, and of course, share as much logs as you can

**Comment by necipulusoy** [comment]
I can't install CLI-2 on my computer (ubuntu-wsl). Can someone help me on this issue?

**Comment by necipulusoy** [comment]
<img width="656" alt="5" src="https://user-images.githubusercontent.com/113590193/211828894-8b9a1cbb-e5e1-4332-8fb7-c2d7ee2b662a.png">

**Comment by maazu** [comment]
If you're installing this on an EC2 instance and encounter this error, ensure that you're installing the appropriate version according to your architecture. This is important because 64-bit Linux and Linux ARM architectures have distinct download links, as outlined in the [AWS CLI installation guidelines](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html).

To determine your EC2 instance's architecture, you can execute the following command:

`lscpu`

**Comment by necipulusoy** [comment]
thank you for your explanation
