### ISSUE TITLE
Deprecating save-state and set-output commands

### ISSUE THREAD

**Issue by czerniga** [unfor19/install-aws-cli-action#17]
In March 2023, functions related to set-output will be disabled. As a result, the following messages appear in the logs:

"Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/"

Warning is related to this function call:
 echo "::set-output name=version::$(aws --version)"

The call of this function should be changed as described in the following page:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by unfor19** [comment]
@czerniga See version [1.0.4 action.yml](https://github.com/unfor19/install-aws-cli-action/blob/v1.0.4/action.yml#L52) - it's updated to this:

```bash
echo "version=$(aws --version)" >> $GITHUB_OUTPUT
```

Have you seen `set-output` anywhere else?

**Comment by AdrianHL** [comment]
I have been investigating a similar error but the step was missing from the UI. I went to the log and saw

```2022-11-30T11:09:17.6708366Z Download action repository 'unfor19/install-aws-cli-action@v1' (SHA:f2649938c0ed0514cfc5448f0b96516580d34e53)```

So when you use `unfor19/install-aws-cli-action@v1` it does not use the latest but the v1 release instead; same SHA see https://github.com/unfor19/install-aws-cli-action/releases/tag/v1#:~:text=v1-,f264993,-update%20readme%20to

**Comment by czerniga** [comment]
Actually, version 1.0.4 is working properly. Using v1 does not download the latest version (1.0.4) and it is necessary to manually change to 1.0.4.

**Comment by AdrianHL** [comment]
So maybe it needs a better communication as most users will assume that `@v1` will automatically use the latest. The readme states that. Or a fix/action is needed to ensure that `@v1` tag pull the latest v1. Not sure how the later can be done or what is needed.

P.S. I have updated our action to use `@v1.0.4` and I don't see the warning now. And the log says
```
2022-11-30T12:53:15.2361660Z Download action repository 'unfor19/install-aws-cli-action@v1.0.4' (SHA:8a86d81a0f1393cff1f44c77010cb2707e8a1066)
```

**Comment by unfor19** [comment]
@AdrianHL I assume by `UI` you mean the README, and the README refers to AWS CLI version, not this action's version.

Having said that, I do want to make things as clear as possible, so I've added this commit - https://github.com/unfor19/install-aws-cli-action/commit/ee0eb151cf1bca186ccf8c35d314b08d62e0e878

![image](https://user-images.githubusercontent.com/15122452/204968274-4031d3fb-d4c6-4982-a19f-c78b132d9e8a.png)

So to be 100% accurate, the `latest v1` refers to AWS CLI's version, not this action's version, sorry for the confusion.

I'm too scared to set `v1` to `v1.0.4` as it might affect existing users, so I prefer to leave it as it is. If anyone else has a better idea of how to set `@v1` of this action to `@v1.0.4` without breaking existing pipelines, feel free to share your thoughts. There aren't breaking changes between `v1` and `v1.0.4`, though I do need to battle-test it before affecting a lot of existing users.

**Comment by unfor19** [comment]
@axkirillov I incline to agree
I'll handle it tomorrow
Feel free to ping here again on Sunday if you don't see any change tomorrow

**Comment by unfor19** [comment]
@axkirillov @AdrianHL @czerniga Thank you for bringing this up, I think you did a huge favor to everyone

I've set the tag `v1` to point to master, so `v1` will include the latest release at all times - https://github.com/unfor19/install-aws-cli-action/releases/tag/v1

I'll make sure not to push directly to master when it comes to changing the behavior of the action.

Again, thanks everyone, leaving this ticket open for a few more days
