### ISSUE TITLE
Release versioning

### ISSUE THREAD

**Issue by jasiamah** [unfor19/install-aws-cli-action#19]
Hi guys

Thanks for the good work on this ! 

Just a note, is the release numbers following semantic versioning? 

It goes from ... v1.0.3 -> v1.0.4 -> v1

**Comment by unfor19** [comment]
Hey @jasiamah , thank you!

I'm following the regular github actions convention where v1 stands for the latest version of v1, at the time of writing it's v1.0.4

Let me know if that answers you question

**Comment by unfor19** [comment]
@jasiamah I'm leaving this ticket open for a few days

Let me know if you have more questions

**Comment by jasiamah** [comment]
Hi

Okay, it was confusing because v1 would be thought to be v1.0.0

But thanks for clarifying
