### ISSUE TITLE
Provided version does not exist on self-hosted runner

### ISSUE THREAD

**Issue by alxmrtn** [unfor19/install-aws-cli-action#20]
Getting this error all of a sudden on our self hosted runners - however https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.7.24.zip is a valid URL that resolves on my laptop and via curl within the deployed pod.

**Logs:**
```
Run sudo --preserve-env /runner/_work/_actions/unfor19/install-aws-cli-action/v1.0.4/entrypoint.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    AWS_CLI_VERSION: 2.7.24
    AWS_CLI_ARCH: amd64
    VERBOSE: true
    LIGHTSAILCTL: false
    ROOTDIR: 
    WORKDIR: 
[LOG] Thu Jan 12 23:39:14 UTC 2023 :: Provided ROOTDIR: 
[LOG] Thu Jan 12 23:39:14 UTC 2023 :: Provided WORKDIR: 
[LOG] Thu Jan 12 23:39:14 UTC 2023 :: Final WORKDIR path: /runner/_work/org/repo/unfor19-awscli
[LOG] Thu Jan 12 23:39:14 UTC 2023 :: Validating semantic version - 2.7.24
[LOG] Thu Jan 12 23:39:14 UTC 2023 :: Valid version input
[LOG] Thu Jan 12 23:39:14 UTC 2023 :: Checking if the provided version exists in AWS
Error:  Thu Jan 12 23:39:14 UTC 2023 :: Provided version does not exist - https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.7.24.zip
Error: Process completed with exit code 1.```

**Comment by igaskin** [comment]
@alxmrtn try pinning the image used by the image used by the `actions-runner-controller`.  There was a image recently pushed which appears to have a breaking bug in it: https://hub.docker.com/r/summerwind/actions-runner/tags

Using tag `v2.300.2-ubuntu-20.04-e71c646` worked to fix this issue for us. :D

**Comment by unfor19** [comment]
@alxmrtn Thanks for reporting; I'll check it today and push a fix if necessary

Meanwhile, please confirm if @igaskin 's suggestion works for you

**Comment by ggwpp** [comment]
https://github.com/unfor19/install-aws-cli-action/issues/20#issuecomment-1381208286 also works for me. thanks @igaskin

**Comment by unfor19** [comment]
Replicating locally-

1. Create the Dockerfile - `Dockerfile.ghcr`
      ```Dockerfile
      ARG SUMMERWIND_TAG
      
      FROM summerwind/actions-runner:${SUMMERWIND_TAG}
      WORKDIR /tmp
      RUN curl -L -o install-aws.sh https://raw.githubusercontent.com/unfor19/install-aws-cli-action/master/entrypoint.sh && \
          chmod +x install-aws.sh &&  \
          sudo ./install-aws.sh "2.7.24"
      ```

2. Build the Docker image with different arguments
    
    - Fails with **ubuntu20.22**
        
        ```bash
        docker build -t aws-cli-action-ghcr-fail -f Dockerfile.ghcr --platform amd64 --build-arg SUMMERWIND_TAG=v2.300.2-ubuntu-22.04-e71c646  .
        ```

        <details><summary>Fail output - Expand/Collapse</summary>
        
        ```
         > [3/3] RUN curl -L -o install-aws.sh https://raw.githubusercontent.com/unfor19/install-aws-cli-action/master/entrypoint.sh &&     chmod +x install-aws.sh &&      sudo ./install-aws.sh "2.7.24":                                                                                                             
        #6 0.238   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                                
        #6 0.238                                  Dload  Upload   Total   Spent    Left  Speed                                                                  
        100  7429  100  7429    0     0   9960      0 --:--:-- --:--:-- --:--:-- 10012                                                                          
        #6 1.170 [LOG] Fri Jan 13 06:49:14 UTC 2023 :: Provided ROOTDIR: 
        #6 1.192 [LOG] Fri Jan 13 06:49:14 UTC 2023 :: Provided WORKDIR: 
        #6 1.214 [LOG] Fri Jan 13 06:49:14 UTC 2023 :: Final WORKDIR path: /tmp/unfor19-awscli
        #6 1.258 [LOG] Fri Jan 13 06:49:14 UTC 2023 :: Validating semantic version - 2.7.24
        #6 1.288 [LOG] Fri Jan 13 06:49:14 UTC 2023 :: Valid version input
        #6 1.344 [ERROR] Fri Jan 13 06:49:14 UTC 2023 :: Provided version does not exist - https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.7.24.zip
        ------
        executor failed running [/bin/sh -c curl -L -o install-aws.sh https://raw.githubusercontent.com/unfor19/install-aws-cli-action/master/entrypoint.sh &&     chmod +x install-aws.sh &&      sudo ./install-aws.sh "2.7.24"]: exit code: 1
        ```

        </details>

     - Passes with **ubuntu20.20** - Regardless of the commit hash, looks like an OS version issue
        
        ```bash
        docker build -t aws-cli-action-ghcr-fail -f Dockerfile.ghcr --platform amd64 --build-arg SUMMERWIND_TAG=v2.300.2-ubuntu-20.04-e71c646  .
        ```

It seems like the script doesn't work on the **20.22** version of GHCR; checking it out.

**Comment by unfor19** [comment]
The output error of the wrapper script [entrypoint.sh](https://github.com/unfor19/install-aws-cli-action/blob/master/entrypoint.sh#L102) is **misleading** 🥲


1. Build the image locally-
      
      ```Dockerfile
      ARG SUMMERWIND_TAG
      
      FROM summerwind/actions-runner:${SUMMERWIND_TAG}
      WORKDIR /tmp
      RUN curl -L -o install-aws.sh https://raw.githubusercontent.com/unfor19/install-aws-cli-action/master/entrypoint.sh && \
          chmod +x install-aws.sh
      ```
     
      ```bash
      docker build -t aws-cli-action-ghcr-fail -f Dockerfile.ghcr --platform amd64 --build-arg SUMMERWIND_TAG=v2.300.2-ubuntu-22.04-e71c646  .
      ```
2. Run a container
      ```bash
      docker run --rm -it --entrypoint bash aws-cli-action-ghcr-fail
      ```
3. Execute the wrapper script
      ```
      sudo ./install-aws.sh 2.7.24
      ...
      [ERROR] Fri Jan 13 06:56:56 UTC 2023 :: Provided version does not exist - https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
      ```
4. Check if [wget](https://www.gnu.org/software/wget/) is installed - `wget --version` and you'll see that it doesn't, hence the error "Provided version does not exist" - the response of [this line](https://github.com/unfor19/install-aws-cli-action/blob/5a3e8d32ebbb30593cb70a7775f81dd5728a24e9/entrypoint.sh#L98) is empty because `wget` doesn't even exist
5. Quick fix to prove that it's `wget` issue
    ```bash
    # While in the running container ...
    apt-get update && apt-get install -y wget

   sudo ./install-aws.sh 2.7.24
   # Output
   # aws-cli/2.7.24 Python/3.9.11 Linux/5.15.49-linuxkit exe/x86_64.ubuntu.22 prompt/off
    ```

It seems like `wget` don't exist on the Ubuntu 22.04 version; The error does not occur on GitHub's runners, only on self-hosted runners, as `wget` is shipped with GitHub's runners but not for GHCR's Ubuntu 22.04.

Oddly enough, I checked if `wget` exists on previous versions of GHCR's Ubuntu 22.04 , and it doesn't, hence I was surprised to read "all of a sudden".

@alxmrtn may you please provide a specific version of the GHCR image that you're using? I'm referring to this list - [https://hub.docker.com/r/summerwind/actions-runner/tags](https://hub.docker.com/r/summerwind/actions-runner/tags)

**Comment by round-corgi** [comment]
Thanks for the awesome turnaround @unfor19 !

**Comment by unfor19** [comment]
@alxmrtn Leaving this issue open for one more day, seems like the problem was fixed
Let me know otherwise
