### ISSUE TITLE
$GITHUB_OUTPUT: ambiguous redirect

### ISSUE THREAD

**Issue by dannybrody** [unfor19/install-aws-cli-action#22]
For some reason I am starting to see the following issue:
```
Run echo "version=$(aws --version)" >> $GITHUB_OUTPUT
  echo "version=$(aws --version)" >> $GITHUB_OUTPUT
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GITHUB_SSH_ID_RSA: ***
  
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  
  ***
  
    AWS_DEFAULT_REGION: us-east-1
    AWS_REGION: us-east-1
    AWS_CLI_VERSION: 2
    AWS_CLI_ARCH: amd64
    VERBOSE: false
    LIGHTSAILCTL: false
    ROOTDIR: 
    WORKDIR: 
/runner/_work/_temp/41668ffc-e81c-4612-92dc-459595bad63b.sh: line 1: $GITHUB_OUTPUT: ambiguous redirect
Error: Process completed with exit code 1.

```

It appears to be from [this](https://github.com/unfor19/install-aws-cli-action/blob/master/action.yml#L52) line.

Possible solution [here](https://github.com/orgs/community/discussions/36746)

**Comment by dannybrody** [comment]
Looks like the problem is not due to this action.  Closing out

**Comment by rvichery** [comment]
> Looks like the problem is not due to this action. Closing out

Running into something similar, what was the fix for you?

**Comment by jzarate-gfm** [comment]
@rvichery The posted issue was due to unintentionally using an older github runner version (v2.293.0) that did not support GITHUB_OUTPUT yet (added in [v2.297.0](https://github.com/actions/runner/releases/tag/v2.297.0))
