### ISSUE TITLE
Use Node 20

### ISSUE THREAD

**Issue by Gershon-A** [unfor19/install-aws-cli-action#29]
Node 16 has reached its [end of life](https://github.com/nodejs/Release/#end-of-life-releases), prompting us to initiate its deprecation process for GitHub Actions. Our plan is to transition all actions to run on Node 20 by Spring 2024. We will actively monitor the migration's progress and gather community feedback before finalizing the transition date. Starting October 23rd, workflows containing actions running on Node 16 will display a warning to alert users about the upcoming migration.

**Comment by unfor19** [comment]
Hi @Gershon-A , sorry for the major delay; I don't think it's relevant to this action as it doesn't use Node 20.

I'll keep this open for a few days in case you want to discuss about it.
